export const utdBuildings = [
    "Activity Center (AB)",
    "Administration Building (AD)",
    "Berkner Hall (BE)",
    "Bioengineering and Sciences Building (BSB)",
    "Blackstone LaunchPad",
    "Brain Performance Institute",
    "Callier Center Dallas",
    "Callier Center Richardson (CR)",
    "Callier Center Richardson Addition (CRA)",
    "Cecil H. Green Hall (GR)",
    "Center for BrainHealth",
    "Center for Vital Longevity",
    "Classroom Building (CB)",
    "Construction Maintenance Building 1 (CM1)",
    "Construction Maintenance Building 2 (CM2)",
    "Construction Maintenance Building 3 (CM3)",
    "Crow Museum of Asian Art",
    "Davidson-Gundy Alumni Center (DGA)",
    "Edith O'Donnell Arts & Technology Building (ATC)",
    "Engineering and Computer Science North (ECSN)",
    "Engineering and Computer Science South (ECSS)",
    "Engineering and Computer Science West (ECSW)",
    "Environmental Health and Safety Building (SG)",
    "Erik Jonsson Academic Center (JO)",
    "Eugene McDermott Library (MC)",
    "Facilities Management (FM)",
    "Facilities Management Custodial and Surplus (FMCS)",
    "Facilities Management Events Building (FME)",
    "Facilities Management Greenhouses (FMGH)",
    "Facilities Management Pole Barn (FMPB)",
    "Facilities Management Shop Building (FMSB)",
    "Facilities Management Storage Building (FMF)",
    "Founders Annex (FA)",
    "Founders Building (FO)",
    "Founders North (FN)",
    "Housing Storage Warehouse",
    "Karl Hoblitzelle Hall (HH)",
    "Modular Lab 1 (ML1)",
    "Modular Lab 2 (ML2)",
    "Natural Science and Engineering Research Lab (RL)",
    "Naveen Jindal School of Management (JSOM)",
    "North Lab (NL)",
    "North Office Building (NB)",
    "Physics Annex (PHA)",
    "Physics Building (PHY)",
    "Police (PD)",
    "Research and Operations Center (ROC)",
    "Research and Operations Center West (ROW)",
    "Richardson Innovation Quarter Headquarters",
    "Sammons BrainHealth Imaging Center",
    "Science Learning Center (SLC)",
    "Sciences Building (SCI)",
    "Service Building (SB)",
    "Student Services Building (SSB)",
    "Student Services Building Addition (SSA)",
    "Student Union (SU)",
    "Synergy Park North (SPN)",
    "Synergy Park North 2 (SP2)",
    "University Theatre (TH)",
    "Visitor Center and University Bookstore (VCB)",
    "Waterview Science and Technology Center (WSTC)"
];